### PR TITLE
Fix renaming a folder while modified in the last minute

### LINKED ISSUE #380: Can't rename a folder with things in it
Hi,

the steps to reprodude:

1. I create a folder `foo` in files
2. In `foo`, I upload two files `bar` and `baz`
3. In `foo`, I create one sub-directory `qux`
4. In `foo/qux`, I upload a file `quux`
5. At the root, I rename `foo` in `foo-renamed`
6. I have a `foo-renamed` folder with my things in it
7. I wait 30s and come back in files
8. I have a `foo` folder, but no `foo-renamed` folder
9. Inside `foo`, I have `qux` but no `bar` or `baz`
10. Inside `foo/qux`, I have no `quux`

### PR DESCRIPTION
**Pull request by nono**
Fix #380

### CODE REVIEW

File: server/helpers/update_parents.coffee [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+module.exports.resetTimeout = ->
+    clearTimeout(timeout) if timeout?
+    timeout = setTimeout module.exports.flush, 60 * 1000
+
+
+# Save in RAM lastModification date for parents
+# Update folder parent once all files are uploaded
+module.exports.flush = (callback) ->
+    async.eachSeries parentFolders, (folder, done) ->
+        folder.save done
```
Comment (aenario) [inline server/helpers/update_parents.coffee]: using .save instead instead .updateAttributes cause loss of special field added by other applications.

**Comment by aenario** [comment]
Travis is red and i recommend using updateAttributes, but it is a separate improvement as previous code used .save.

**Comment by nono** [comment]
@aenario done
